### ISSUE TITLE
Incorrect Next track ID after import chapters

### ISSUE THREAD

**Issue by L2501** [sandreas/tone#51] opened 2023-07-07 09:49 UTC
in movie header atom after tagging chapters to m4b file the Next track ID is incorrectly set to "2" but ID 2 is already in use.

mediainfo --Details=10 file.m4b | grep "k ID"
```
0000008C   Next track ID:                        2 (0x00000002)
000000AC    Track ID:                            1 (0x00000001)
008995BD    Track ID:                            2 (0x00000002)
```
Ref: https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-32947

**Comment by sandreas** [comment] 2023-07-07 21:58
Thanks for reporting. I have to show this to the atldotnet maintainer, this may be fixed in a recent version.

**Comment by sandreas** [comment] 2023-07-17 05:42
@L2501 
Mmh I was not able to reproduce this. Could you help me out with a (smallish) file and the according command that produces this problem?

**Comment by L2501** [comment] 2023-07-17 06:23
import from the mp4v2 format, any file should do
```tone tag file.m4b --meta-chapters-file file.chapters.txt```

**Comment by L2501** [comment] 2023-07-17 06:47
@sandreas https://mega.nz/file/UiAVnKyK#A8AvSDr_k8u5LsBljLy4UmFcOCZ7-kh02LUTlLd3o-s

**Comment by sandreas** [comment] 2023-07-17 17:06
@L2501 
Thanks, I'll take a look as soon as possible, but maybe we have to redirect this to atldotnet / @Zeugma440, I'll keep you up to date.

**Comment by sandreas** [comment] 2024-12-04 19:02
Should be fixed in `0.2.0`.

**Closed by sandreas** 2024-12-04 19:02 UTC
Labels: bug, awaiting feedback, atldotnet
